### 휴가 상태 ONGING
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "jobName": "vacation.status-manage.job",
  "properties": {
    "run.id": "ADMIN20240303-001",
    "processDate": "2024-03-03 00:00:00"
  }
}

### 휴가 종료일에 맞춰 휴가 상태 조정 및 잔여 연차 차감
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
"jobName": "leave.adjust.job",
"properties": {
  "run.id": "ADMIN20240304-01",
  "executeDateTime": "2024-03-04 00:00:00"
  }
}