CREATE TABLE `jxx_vacation_master` (
   `VACATION_ID` bigint UNSIGNED NOT null AUTO_INCREMENT COMMENT '휴가 식별자',
   `COMPANY_ID` varchar(8) NOT NULL COMMENT '회사 식별자',
   `CREATE_TIME` datetime(6) NOT NULL COMMENT '레코드 생성 시간',
   `LEAVE_DEDUCT` varchar(16) NOT NULL COMMENT '연차 차감 여부',
   `REQUESTER_ID` varchar(16) NOT NULL COMMENT '연차 신청자 ID',
   `VACATION_STATUS` char(16) NOT NULL COMMENT '휴가 신청 상태',
   `VACATION_TYPE` varchar(16) NOT NULL COMMENT '연차 유형',
      PRIMARY KEY (`VACATION_ID`),
   KEY `IDX_REQUESTER_ID` (`REQUESTER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `jxx_member_leave_master` (
    `MEMBER_PK` bigint NOT NULL AUTO_INCREMENT COMMENT '사용자 테이블 PK',
    `ENTERED_DATE` date DEFAULT NULL COMMENT '입사일자',
    `EXPERIENCE_YEARS` int DEFAULT NULL COMMENT '경력 연차',
    `IS_ACTIVE` bit(1) NOT NULL COMMENT '사용자 활성화 여부(0:비활성화 1:활성화)',
    `REMAINING_LEAVE` float DEFAULT NULL COMMENT '연차 잔여일',
    `TOTAL_LEAVE` float DEFAULT NULL COMMENT '연차 잔여일',
    `MEMBER_ID` varchar(16) DEFAULT NULL COMMENT '사용자 식별자',
    `NAME` varchar(32) DEFAULT NULL COMMENT '사용자 이름',
    `COMPANY_ID` varchar(8) DEFAULT NULL COMMENT '회사 식별자',
    `DEPARTMENT_ID` varchar(16) DEFAULT NULL COMMENT '부서 식별자',
    PRIMARY KEY (`MEMBER_PK`),
    UNIQUE KEY `UK_dim8gm89g70dn0834duf9hpxs` (`MEMBER_ID`),
    UNIQUE KEY `IDX_MEMBER_LEAVE_MEMBER_ID` (`MEMBER_ID`),
    KEY `IDX_MEMBER_LEAVE_MEMBER_NAME` (`NAME`),
    KEY `FKr7jrpsrk6lw35olsa1bt80x3a` (`COMPANY_ID`,`DEPARTMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `jxx_message_q` (
     `MESSAGE_Q_PK` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메시지Q PK',
     `BODY` json DEFAULT NULL COMMENT '메시지 본문',
     `EVENT_TIME` datetime(6) NOT NULL COMMENT '메시지 생성 시간',
     `MESSAGE_DESTINATION` varchar(16) DEFAULT NULL COMMENT '목적지',
     `MESSAGE_PROCESS_STATUS` char(16) NOT NULL COMMENT '메시지 처리 상태',
     `PROCESS_START_TIME` datetime(6) DEFAULT NULL COMMENT '메시지 처리 시간 시간',
     `RETRY_ID` bigint DEFAULT NULL COMMENT '재시도 할 MESSAGEQ PK',
     PRIMARY KEY (`MESSAGE_Q_PK`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `jxx_message_q_result` (
    `MESSAGE_Q_RESULT_PK` bigint NOT NULL AUTO_INCREMENT COMMENT '메시지Q 결과 PK',
    `BODY` json DEFAULT NULL COMMENT '메시지 본문',
    `EVENT_TIME` datetime(6) NOT NULL COMMENT '메시지 생성 시간',
    `MESSAGE_DESTINATION` varchar(16) DEFAULT NULL COMMENT '목적지',
    `MESSAGE_PROCESS_STATUS` char(16) NOT NULL COMMENT '메시지 처리 상태',
    `ORIGINAL_MESSAGE_PK` bigint NOT NULL COMMENT '메시지Q PK',
    `PROCESS_END_TIME` datetime(6) DEFAULT NULL COMMENT '메시지 처리 종료 시간',
    `PROCESS_START_TIME` datetime(6) DEFAULT NULL COMMENT '메시지 처리 시작 시간',
    PRIMARY KEY (`MESSAGE_Q_RESULT_PK`),
    KEY `IDX_O_MESSAGE_PK` (`ORIGINAL_MESSAGE_PK`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;