### DB CLEAR 시 아래 API 호출하여 테스트 조직, 사용자생성
POST http://localhost:8080/members

### 휴가 신청 POST

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requestId": "U00001",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-01-08T00:00",
    "endDateTime": "2024-01-10T00:00"
  }
}

###

POST http://localhost:8080/api/vacations/4/raise
Content-Type: application/json