### 애플리케이션 실행 시 아래부터 하나씩 호출하면 테스트 데이터 완성
POST http://localhost:8080/members

### 휴가 신청 POST 1

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requestId": "U00001",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-02-25T00:00",
    "endDateTime": "2024-02-27T00:00"
  }
}

### 휴가 신청 POST 2

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requestId": "U00002",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-03-02T00:00",
    "endDateTime": "2024-03-05T00:00"
  }
}

###

POST http://localhost:8080/api/vacations/1/raise
Content-Type: application/json


###
PATCH http://localhost:8080/message-q-results/2/retry
Content-Type: application/json

###
GET http://localhost:8080/message-q-results/fail?page=0&size=3
Content-Type: application/json