### 애플리케이션 실행 시 아래부터 하나씩 호출하면 테스트 데이터 완성
POST http://localhost:8080/members

### 휴가 신청 POST 1

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requesterId": "U00130",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-03-11T00:00",
    "endDateTime": "2024-03-12T00:00"
  }
}

### 휴가 조회
GET http://localhost:8080/api/vacations

### 휴가 상신
POST http://localhost:8080/api/vacations/24/raise
Content-Type: application/json

### 휴가 신청 POST 2

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requesterId": "U00002",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-03-02T00:00",
    "endDateTime": "2024-03-05T00:00"
  }
}

###
POST http://localhost:8080/api/vacations/9/raise
Content-Type: application/json

###
PATCH http://localhost:8080/message-q-results/2/retry
Content-Type: application/json

###
GET http://localhost:8080/message-q-results/fail?page=0&size=3
Content-Type: application/json

### 휴가 취소
POST http://localhost:8080/api/vacations/2/cancel

### 휴가 신청서 수정
PATCH http://localhost:8080/api/vacations/1
Content-Type: application/json

{
  "requesterId": "U00087",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-03-05T00:00",
    "endDateTime": "2024-03-08T00:00"
  }
}