### 휴가 시작일에 돌아야 하는 배치 휴가 상태 APPROVE -> ONGING
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "jobName": "vacation.start.job",
    "run.id": "ADMIN20240412-002",
    "processDate": "2024-04-12 00:00:00"
  }
}

### 휴가 상태 ONGING 필수 파라미터 누락 CASE
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "run.id": "ADMIN20240407-001",
    "processDate": "2024-04-07 00:00:00"
  }
}


### 휴가 종료일에 맞춰 휴가 상태 조정 및 잔여 연차 차감
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "jobName": "vacation.end.job",
    "run.id": "ADMIN20240411-01",
    "executeDateTime": "2024-04-12 00:00:00"
  }
}

### 휴가 종료일에 맞춰 휴가 상태 조정 및 잔여 연차 차감 필수 파라미터 누락 CASE
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "run.id": "ADMIN20240404-01",
    "executeDateTime": "2024-03-04 00:00:00"
  }
}