### 휴가 시작일에 돌아야 하는 배치 휴가 상태 APPROVE -> ONGING
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "jobName": "vacation.start.job",
  "properties": {
    "jobName": "vacation.start.job",
    "run.id": "ADMIN20240419-001",
    "processDate": "2024-04-19 00:00:00"
  }
}

### 휴가 상태 ONGING 필수 파라미터 누락 CASE
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "run.id": "ADMIN20240407-001",
    "processDate": "2024-04-07 00:00:00"
  }
}


### 휴가 종료일에 맞춰 휴가 상태 조정 및 잔여 연차 차감 예를 들어, 16일까지 휴가라면 executeDateTime = 2024-04-17 00:00:00 넣어서 처리
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "jobName": "vacation.end.job",
    "run.id": "ADMIN20240418-002",
    "executeDateTime": "2024-04-18 00:00:00"
  }
}

### 휴가 종료일에 맞춰 휴가 상태 조정 및 잔여 연차 차감 필수 파라미터 누락 CASE
POST http://localhost:8070/batch/job/run
Content-Type: application/json

{
  "properties": {
    "run.id": "ADMIN20240404-01",
    "executeDateTime": "2024-03-04 00:00:00"
  }
}

###
POST http://localhost:8070/admin/batch/jobs
Content-Type: application/json

{
  "jobName": "vacation.start.job",
  "jobDescription": "연차 시작 처리 배치",
  "used": true,
  "executeType": "시간",
  "executionTime": "00:00:00",
  "executionDuration": null,
  "jobParams": [
    {
      "parameterKey": "run.id",
      "paramDescription": "잡 실행 고유 ID",
      "placeHolder": "ADMIN20240627-001",
      "required": true
    },
    {
      "parameterKey": "jobName",
      "paramDescription": "실행할 Spring Bean Name",
      "placeHolder": "",
      "required": true
    },
    {
      "parameterKey": "processDate",
      "paramDescription": "휴가 시작 일자",
      "placeHolder": "2024-06-27",
      "required": true
    }
  ]
}

###
POST http://localhost:8070/admin/batch/jobs
Content-Type: application/json

{
  "jobName": "vacation.end.job",
  "jobDescription": "연차 종료 처리 배치",
  "used": true,
  "executeType": "시간",
  "executionTime": "00:05:00",
  "executionDuration": null,
  "jobParams": [
    {
      "parameterKey": "run.id",
      "paramDescription": "잡 실행 고유 ID",
      "placeHolder": "ADMIN20240627-001",
      "required": true
    },
    {
      "parameterKey": "jobName",
      "paramDescription": "실행할 Spring Bean Name",
      "placeHolder": "",
      "required": true
    },
    {
      "parameterKey": "executeDateTime",
      "paramDescription": "휴가 종료 일자, 배치 실행 일자 기준으로 전일을 설정하면 된다. 예를 들어, 배치가 6월28일 00시에 시작되는 경우 6월 27일에 종료되는 휴가를 종료 처리해야하기 때문이다.",
      "placeHolder": "2024-06-27",
      "required": true
    }
  ]
}