### 애플리케이션 실행 시 아래부터 하나씩 호출하면 테스트 데이터 완성
POST http://localhost:8080/members

### 휴가 신청 POST 1

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requesterId": "SPY00011",
  "vacationType": "MORE_DAY",
  "leaveDeduct": "DEDUCT",
  "requestVacationDurations": [
    {
      "startDateTime": "2024-04-19T00:00",
      "endDateTime": "2024-04-19T00:00"
    }
  ]
}



### 휴가 상신
POST http://localhost:8080/api/vacations/611/raise
Content-Type: application/json

### 휴가 신청 POST 2

POST http://localhost:8080/api/vacations
Content-Type: application/json

{
  "requesterId": "U00001",
  "vacationType" : "MORE_DAY",
  "leaveDeduct" : "DEDUCT",
  "requestVacationDurations": [
    {
      "startDateTime": "2024-11-11T00:00",
      "endDateTime": "2024-11-11T00:00"
    }
  ]
}

###
POST http://localhost:8080/api/vacations/VACSPY10/raise
Content-Type: application/json

###
PATCH http://localhost:8080/message-q-results/2/retry
Content-Type: application/json

###
GET http://localhost:8080/message-q-results/fail?page=0&size=3
Content-Type: application/json

### 휴가 취소
POST http://localhost:8080/api/vacations/2/cancel

### 휴가 신청서 수정
PATCH http://localhost:8080/api/vacations/1
Content-Type: application/json

{
  "requesterId": "U00100",
  "vacationDuration": {
    "vacationType": "MORE_DAY",
    "startDateTime": "2024-03-24T00:00",
    "endDateTime": "2024-03-25T00:00"
  }
}

### SIGN IN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "U00119",
  "password": "U00120"
}

### 부서원 조회
GET http://localhost:8080/api/departments/J01020/member-leaves?cid=JXX
Content-Type: application/json


### 부서 휴가 조회
GET http://localhost:8080/api/vacations?cid=SPY&pid=SPY01002

### 부서 휴가 검색
GET http://localhost:8080/api/vacations?companyId=SPY

### 부서 휴가 검색
GET http://localhost:8080/api/vacations?companyId=SPY&departmentId=SPY00202&vacationStatus=CREATE,REQUEST

### 휴가 상신 (결재 서버 올라와있어야 함)
POST http://localhost:8080/api/vacations/1210/raise
Content-Type: application/json
