

### 회사코드 생성
POST http://localhost:8080/test/company-codes
Content-Type: application/json

{
  "companyId": "BNG",
  "companyName": "바바베이커리"
}

### 회사코드 조회
GET http://localhost:8080/test/company-codes

### 부서검색 API
GET http://localhost:8080/api/organizations