
### 작업 티켓 생성 API 1
POST http://localhost:8080/api/work-tickets
Content-Type: application/json

{
  "chargeCompanyId": "SPY",
  "chargeDepartmentId": "SPY00102",
  "requestTitle" : "의료 데이터 추출 요청",
  "requestContent": "2023년 심혈질관 관련 데이터 추출 요청 드립니다. 지역: 전국 대상: 여성 40~49세, 기록일자 2023.01 ~ 2023.12",
  "workRequester": {
    "companyId": "SPY",
    "id": "SPY00014",
    "name": "이승기"
  }
}

### 작업 티켓 생성 API 2
POST http://localhost:8080/api/work-tickets
Content-Type: application/json

{
  "chargeCompanyId": "SPY",
  "chargeDepartmentId": "SPY00105",
  "requestTitle" : "2024년 하반기 신입 직원 응급 의료 교육 자료 요청 ",
  "requestContent": "상기 제목의 자료 요청드립니다.",
  "workRequester": {
    "companyId": "SPY",
    "id": "SPY00302",
    "name": "전창환"
  }
}

###
GET http://localhost:8080/api/work-tickets/search?memberId=U00006


### 작업 접수 API
POST http://localhost:8080/api/work-tickets/d67a2f38-0ab2-49e8-8796-c89076060eaf/receive
Content-Type: application/json

{
  "receiverCompanyId" :  "SPY",
  "receiverDepartmentId" :  "SPY00105",
  "receiverId": "SPY00488",
  "receiverName": "김한샘"
}

### 작업 분석 단계 진입 API
PATCH http://localhost:8080/api/work-tickets/d67a2f38-0ab2-49e8-8796-c89076060eaf/begin-analysis
Content-Type: application/json

{
  "receiverCompanyId": "SPY",
  "receiverDepartmentId": "SPY00105",
  "receiverId": "SPY00488"
}