
###
POST http://localhost:8080/api/work-tickets
Content-Type: application/json

{
  "chargeCompanyId": "SPY",
  "chargeDepartmentId": "SPY00102",
  "requestTitle" : "의료 데이터 추출 요청",
  "requestContent": "2023년 심혈질관 관련 데이터 추출 요청 드립니다. 지역: 전국 대상: 여성 40~49세, 기록일자 2023.01 ~ 2023.12",
  "workRequester": {
    "companyId": "SPY",
    "id": "SPY00014",
    "name": "이승기"
  }
}

###
GET http://localhost:8080/api/work-tickets/search?memberId=U00006


###
POST http://localhost:8080/api/work-tickets/af5b78bf-dd34-4e3e-b8cf-021b656d4f62/receive
Content-Type: application/json

{
  "receiverCompanyId" :  "SPY",
  "receiverDepartmentId" :  "SPY00102",
  "receiverId": "SPY00033",
  "receiverName": "김태리"
}