
### 로그인 - 관리자
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "manager",
  "password": "manager"
}

### 로그인 - 일반사용자
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "SPY00033",
  "password": "SPY00033"
}


### 테이블 매핑 정보 추가
POST http://localhost:8080/admin/message-destination/GW_NOTIFICATION_DB/table-mappings
Content-Type: application/json

{
  "tableName": "NOTIFICATION_TEST",
  "serviceId" : "UPDATE_NOTIFICATION",
  "dmlType" : "UPDATE"
}

### 컬럼 매핑 정보 추가1
POST http://localhost:8080/admin/message-destination/GW_NOTIFICATION_DB/table-mappings/CREATE_NOTIFICATION/column-mappings
Content-Type: application/json

{
  "columnName": "MEMBER_ID",
  "columnType" : "varchar"
}

### 컬럼 매핑 정보 추가2
POST http://localhost:8080/admin/message-destination/GW_NOTIFICATION_DB/table-mappings/CREATE_NOTIFICATION/column-mappings
Content-Type: application/json

{
  "columnName": "CONTENT",
  "columnType" : "varchar"
}

### 컬럼 매핑 정보 추가3
POST http://localhost:8080/admin/message-destination/GW_NOTIFICATION_DB/table-mappings/UPDATE_NOTIFICATION/column-mappings
Content-Type: application/json

{
  "columnName": "CONTENT",
  "columnType" : "varchar"
}

### 테스트
POST http://localhost:8080/admin/message-destination/check-connection
Content-Type: application/json

{
 "driverClassName": "com.mysql.cj.jdbc.Driver",
 "jdbcUrl":"jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
 "userName": "root",
 "password":"fkxhs123!@#A442"
}

###
POST http://localhost:8080/admin/message-destination
Content-Type: application/json

{
  "destinationId" : "GW_CONFIRM_DB",
  "destinationName" : "그룹웨어 전자결재 DB",
  "connectionType" : "RDB",
  "connectionInformation" : {
    "url" : "jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
    "username" : "root",
    "password" : "fkxhs123!@#A",
    "driverClassName" : "com.mysql.cj.jdbc.Driver"
  }
}

###
POST http://localhost:8080/admin/message-destination
Content-Type: application/json

{
  "destinationId" : "GW_NOTIFICATION_DB",
  "destinationName" : "알림 서버 DB",
  "connectionType" : "RDB",
  "connectionInformation" : {
    "url" : "jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
    "username" : "root",
    "password" : "fkxhs123!@#A",
    "driverClassName" : "com.mysql.cj.jdbc.Driver"
  }
}