
### 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "SPY00033",
  "password": "SPY00033"
}

### 테이블 매핑 정보 추가
POST http://localhost:8080/admin/message-destination/GW_NOTIFICATION_DB/table-mappings
Content-Type: application/json

{
  "tableName" : "NOTIFICATION_TEST"
}

### 테스트
POST http://localhost:8080/admin/message-destination/check-connection
Content-Type: application/json

{
 "driverClassName": "com.mysql.cj.jdbc.Driver",
 "jdbcUrl":"jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
 "userName": "root",
 "password":"fkxhs123!@#A442"
}

###
POST http://localhost:8080/admin/message-destination
Content-Type: application/json

{
  "destinationId" : "GW_CONFIRM_DB",
  "destinationName" : "그룹웨어 전자결재 DB",
  "connectionType" : "RDB",
  "connectionInformation" : {
    "url" : "jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
    "username" : "root",
    "password" : "fkxhs123!@#A",
    "driverClassName" : "com.mysql.cj.jdbc.Driver"
  }
}

###
POST http://localhost:8080/admin/message-destination
Content-Type: application/json

{
  "destinationId" : "GW_NOTIFICATION_DB",
  "destinationName" : "알림 서버 DB",
  "connectionType" : "RDB",
  "connectionInformation" : {
    "url" : "jdbc:mysql://localhost:3306/JXX_CONFIRM?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8",
    "username" : "root",
    "password" : "fkxhs123!@#A",
    "driverClassName" : "com.mysql.cj.jdbc.Driver"
  }
}