
### 관리자 API TEST
POST localhost:8080/admin/vacations/set-common-vacation
#Cookie: B9409498F8155CC26460CADD63DCB987
Content-Type: application/json

{
  "companyId" :  "JXX",
  "mustApproval" : false,
  "deducted" :  true,
  "vacationDates" : ["2024-09-10"]
}

### 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "U00001",
  "password": "U00001"
}


### 특별 휴가 정책 추가 JXX
POST http://localhost:8080/admin/vacations/type-policies
Content-Type: application/json

{
  "companyId": "JXX",
  "vacationTypePolicyForms": [
    {
      "vacationType": "MARRIAGE_SELF",
      "vacationTypeName" : "결혼",
      "vacationDay": 7
    },
    {
      "vacationType": "MARRIAGE_CHILD",
      "vacationTypeName" : "자녀의 결혼",
      "vacationDay": 5
    },
    {
      "vacationType": "CHILD_BIRTH_SELF",
      "vacationTypeName" : "출산 휴가",
      "vacationDay": 180
    },
    {
      "vacationType": "CHILD_BIRTH_SPOUSE",
      "vacationTypeName" : "배우자의 출산",
      "vacationDay": 60
    },
    {
      "vacationType": "REVERSE_FORCES",
      "vacationTypeName" : "예비군 훈련",
      "vacationDay": 1
    },
    {
      "vacationType": "DEATH_GRAND_PARENT_SELF",
      "vacationTypeName" : "조부모상",
      "vacationDay": 3
    },
    {
      "vacationType": "DEATH_PARENT_SELF",
      "vacationTypeName" : "부모친상",
      "vacationDay": 7
    },
    {
      "vacationType": "DEATH_SIBLING_SELF",
      "vacationTypeName" : "형제상",
      "vacationDay": 5
    }
  ]
}


### 관리자 로그인!!
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId" : "U00001",
  "password" : "U00001"
}

### 휴가 정책 등록 Excel
POST http://localhost:8080/api/vacations/set-vacation-type-policy
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name:"file"; fileName="휴가정책등록양식.xlsx"
Content-Type: */*; charset=UTF-8

<C:\Users\GW200014\Desktop\휴가정책등록양식.xlsx
--boundary--