
### 관리자 API TEST
POST localhost:8080/admin/vacations/set-common-vacation
#Cookie: B9409498F8155CC26460CADD63DCB987
Content-Type: application/json

{
  "companyId" :  "JXX",
  "mustApproval" : false,
  "deducted" :  true,
  "vacationDates" : ["2024-09-10"]
}

### 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId": "U00001",
  "password": "U00001"
}

### 특별 휴가 정책 추가 SPY
POST http://localhost:8080/admin/vacations/type-policies
Content-Type: application/json

{
  "companyId": "SPY",
  "vacationTypePolicyForms": [
    {
      "vacationType": "MARRIAGE_SELF",
      "vacationDay": 7
    },
    {
      "vacationType": "MARRIAGE_CHILD",
      "vacationDay": 5
    }
  ]
}

### 특별 휴가 정책 추가 BNG
POST http://localhost:8080/admin/vacations/type-policies
Content-Type: application/json

{
  "companyId": "BNG",
  "vacationTypePolicyForms": [
    {
      "vacationType": "MARRIAGE_SELF",
      "vacationDay": 7
    },
    {
      "vacationType": "MARRIAGE_CHILD",
      "vacationDay": 3
    },
    {
      "vacationType": "CHILD_BIRTH_SELF",
      "vacationDay": 365
    },
    {
      "vacationType": "CHILD_BIRTH_SPOUSE",
      "vacationDay": 90
    }
  ]
}



### 관리자 로그인!!
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "memberId" : "U00001",
  "password" : "U00001"
}